# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

blogmenu:
  - name: '東歐·中亞·前蘇聯'
    tag: 'Soviet'
  - name: '42天跨越歐亞大旅行'
    tag: 'Grand Trip'
  - name: '西非'
    tag: 'West Africa'
  - name: '摩洛哥'
    tag: 'Morocco'
    reversed: true
  - name: '北美'
    tag: 'North America'
  - name: '移民社區'
    tag: 'Immigrant Community'
  - name: '藝術、音樂與戲劇'
    tag: 'Arts'
  - name: '我的移民與職涯故事'
    tag: 'Fob'
    reversed: true

social:
- icon: 'facebook'
  link: 'https://www.facebook.com/lifetimesojourner'
- icon: 'instagram'
  link: 'https://instagram.com/travel.wok'
- icon: 'medium'
  link: 'https://medium.com/@jeromecyang'
- icon: 'envelope'
  link: 'mailto:hi@jeromeyang.com'

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: '相關推薦文章'

post_date_prefix: 'Written on'

# Featured on homepage
features:
  - title: 挑戰最高難度自助旅行：一個人的西非三國（貝南、多哥、迦納）
    excerpt: 西非可以說是全世界旅遊難度最高、也最少遊客踏足的地區；然而，這裡有著別的地方看不到的文化景觀、往昔非洲帝國的遺跡，以及見證奴隸貿易歷史的場景，再加上還未被觀光業污染的太嚴重，這使得西非具有一種讓人覺得「因為神秘、因此更應該前往」的獨特魅力。
    image: https://imgur.com/JoLD34z.jpg
    url: /tag/West%20Africa
  - title: 被打翻的族群調色盤：縱橫高加索三國（喬治亞、亞塞拜然、亞美尼亞）
    excerpt: 歐亞交界處、面積不大的一片山區裡，有著積累數千年的獨特文化，無數個互不相通的語言，又可以見到拜占庭、波斯、土耳其、蘇聯影響的痕跡，簡直就像個被打翻了的族群調色盤。這究竟是一個怎樣的地方？一起來看看我2019年5月的旅行見聞吧！
    image: assets/img/IMG_3379.JPG
    url: /tag/Caucasus
  - title: 北非，其實沒那麼神秘：感恩節的摩洛哥之旅
    excerpt: 聽到北非，想到的不外乎是撒哈拉沙漠、阿拉伯語、遊牧民族等充滿神秘色彩的元素，而這種神秘感更讓人心生嚮往；不過就在我2018年11月親自前往摩洛哥之後，才發現原來這裡不但一點都不神秘，反而是個觀光化程度高到嚇人的國家⋯⋯
    image: https://lifetimesojournertravel.files.wordpress.com/2018/12/b9dc3-img_9435.jpg
    url: /tag/Morocco
  - title: 從絲路到西伯利亞鐵路：穿越中亞北亞的42天大旅行
    excerpt: 2018年5到6月之間，利用換工作的空檔，我從烏茲別克出發，沿著絲路通過吉爾吉斯進入中國新疆，再由內蒙古進入西伯利亞，然後橫跨整個俄羅斯，旅程結束在芬蘭赫爾辛基。這趟翻過了帕米爾高原、造訪了貝加爾湖、搭乘了西伯利亞鐵路的42天大旅行，是我自主旅行迄今最勇敢的嘗試，也讓我看到短途旅遊中難以察覺的複雜地理現象⋯⋯
    image: https://lifetimesojournertravel.files.wordpress.com/2018/09/f5e1e-f6593152.jpg
    url: /tag/Grand%20Trip
  - title: 我的移民與職涯故事
    excerpt: 2010年8月，我以菜鳥移民的身份來到美國，在人生地不熟的環境裡經歷了各種挑戰與趣事；多年之後回顧，我決定把自己最初幾個月的故事寫下來，和大家分享，也讓自己不要忘記那段既辛苦卻又令人回味無窮的日子。
    image: https://lifetimesojournertravel.files.wordpress.com/2017/12/25907-20170424_172241.jpg
    url: /tag/Fob
